# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'carpentersquare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for carpentersquare

  # Pods for ARuler
pod 'OpenCV', '3.1.0.1'
pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :branch => 'release/swift4'

  target 'carpentersquareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'carpentersquareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
